const questions = [
    {
      id: "Q1",
      text: `We met the dog....... on the floor when we got there.`,
      options: [
        { id: 0, text: "laying", isCorrect: false },
        { id: 1, text: "lay", isCorrect: false },
        { id: 2, text: "lying", isCorrect: true },
        { id: 3, text: "lied", isCorrect: false },
      ],
      answer: "lying",
    },
    {
      id: "Q2",
      text: `She always .... until her children get home.`,
      options: [
        { id: 0, text: "waits on", isCorrect: false },
        { id: 1, text: "waits at", isCorrect: false },
        { id: 2, text: "waits in", isCorrect: false },
        { id: 3, text: "waits up", isCorrect: true },
      ],
      answer: "waits up",
    },
    {
      id: "Q3",
      text: `I bought a dozen eggs and every single one of them .... bad.`,
      options: [
        { id: 0, text: "is", isCorrect: false },
        { id: 1, text: "was", isCorrect: true },
        { id: 2, text: "were", isCorrect: false },
        { id: 3, text: "are", isCorrect: false },
      ],
      answer: "was",
    },
    {
      id: "Q4",
      text: `The panel of judges .... ready.`,
      options: [
        { id: 0, text: "they", isCorrect: false },
        { id: 1, text: "are", isCorrect: false },
        { id: 2, text: "is", isCorrect: true },
        { id: 3, text: "were", isCorrect: false },
      ],
      answer: "is",
    },
    {
      id: "Q5",
      text: `I'm waiting .... all day because I'm expecting a special vistor.`,
      options: [
        { id: 0, text: "up", isCorrect: false },
        { id: 1, text: "on", isCorrect: false },
        { id: 2, text: "at", isCorrect: false },
        { id: 3, text: "in", isCorrect: true },
      ],
      answer: "in",
    },
    {
      id: "Q6",
      text: `She connived ..... her friend to dupe the stranger.`,
      options: [
        { id: 0, text: `in`, isCorrect: false},
        { id: 1, text: `at`, isCorrect: false},
        { id: 2, text: `with`, isCorrect: true},
        { id: 3, text: `on`,isCorrect: false},
      ],
      answer: `with`,
    },
    {
      id: "Q7",
      text: `He confided ..... him.`,
      options: [
        { id: 0, text: "with", isCorrect: false },
        { id: 1, text: "on", isCorrect: false },
        { id: 2, text: "in", isCorrect: true },
        { id: 3, text: "at", isCorrect: false },
      ],
      answer: "in",
    },
    {
      id: "Q8",
      text: `The corrupt politician was relieved .... his position.`,
      options: [
        { id: 0, text: "from", isCorrect: false },
        { id: 1, text: "for", isCorrect: false },
        { id: 2, text: "to", isCorrect: false },
        { id: 3, text: "of", isCorrect: true },
      ],
      answer: "of",
    },
    {
      id: "Q9",
      text: `No one .... where he comes from`,
      options: [
        { id: 0, text: "knew", isCorrect: false },
        { id: 1, text: "knows", isCorrect: true },
        { id: 2, text: "know", isCorrect: false },
        { id: 3, text: "known", isCorrect: false },
      ],
      answer: "knows",
    },
    {
      id: "Q10",
      text: `This match is .... to lose.`,
      options: [
        { id: 0, text: "theirs", isCorrect: true },
        { id: 1, text: "their's", isCorrect: false },
        { id: 2, text: "there", isCorrect: false },
        { id: 3, text: "them", isCorrect: false },
      ],
      answer: "theirs",
    },
    {
      id: "Q11",
      text: `He got himself a ..... car.`,
      options: [
        { id: 0, text: "brand new red German sports", isCorrect: true },
        { id: 1, text: "brand new German red sport", isCorrect: false },
        { id: 2, text: "new brand blue sports German", isCorrect: false },
        { id: 3, text: "new brand German red sports", isCorrect: false },
      ],
      answer: "brand new red German sports",
    },
    {
      id: "Q12",
      text: `A ..... panel has been set up to look into the matter.`,
      options: [
        { id: 0, text: "five-men", isCorrect: false },
        { id: 1, text: "five-men's", isCorrect: false },
        { id: 2, text: "five-man", isCorrect: true },
        { id: 3, text: "five-man's", isCorrect: false },
      ],
      answer: "five-man",
    },
    {
      id: "Q13",
      text: `The lecture begins in two .... time.`,
      options: [
        { id: 0, text: "hour's", isCorrect: false },
        { id: 1, text: "hours'", isCorrect: true },
        { id: 2, text: "hour", isCorrect: false },
        { id: 3, text: "hours", isCorrect: false },
      ],
      answer: "hours'",
    },
    {
      id: "Q14",
      text: `This is .......... handiwork.`,
      options: [
        { id: 0, text: "Mike and Jim", isCorrect: false },
        { id: 1, text: "Mike's and Jim's", isCorrect: false },
        { id: 2, text: "Mike and Jim's", isCorrect: true },
        { id: 3, text: "Mike's and Jim", isCorrect: false },
      ],
      answer: "Mike and Jim's",
    },
    {
      id: "Q15",
      text: `The cow is breast-feeding .... calf.`,
      options: [
        { id: 0, text: "it's", isCorrect: false },
        { id: 1, text: "it", isCorrect: false },
        { id: 2, text: "it is", isCorrect: false },
        { id: 3, text: "its", isCorrect: true },
      ],
      answer: "its",
    },
    {
      id: "Q16",
      text: `Ada doesn't mind .... the needy.`,
      options: [
        { id: 0, text: "to help", isCorrect: false },
        { id: 1, text: "helping", isCorrect: true },
        { id: 2, text: "help", isCorrect: false },
        { id: 3, text: "helped", isCorrect: false },
      ],
      answer: "helping",
    },
    {
      id: "Q17",
      text: `He found out, much to his dismay, that he had nobody worth .... friends.`,
      options: [
        { id: 0, text: "calling", isCorrect: true },
        { id: 1, text: "call", isCorrect: false },
        { id: 2, text: "to call", isCorrect: false },
        { id: 3, text: "called", isCorrect: false },
      ],
      answer: "calling",
    },
    {
      id: "Q18",
      text: `He fed his face on ...... wealth.`,
      options: [
        { id: 0, text: "ill-got", isCorrect: false },
        { id: 1, text: "ill-get", isCorrect: false },
        { id: 2, text: "ill gotten", isCorrect: false },
        { id: 3, text: "ill-gotten", isCorrect: true },
      ],
      answer: "ill-gotten",
    },
    {
      id: "Q19",
      text: `...... aside, our team was beaten four goals to nothing by the opponents.`,
      options: [
        { id: 0, text: "Jokes", isCorrect: false },
        { id: 1, text: "Joke", isCorrect: false },
        { id: 2, text: "Joking", isCorrect: true },
        { id: 3, text: "Joked", isCorrect: false },
      ],
      answer: "Joking",
    },
    {
      id: "Q20",
      text: `Every cloud has a silver lining.`,
      options: [
        { id: 0, text: "The cloud is a source of silver", isCorrect: false },
        { id: 1, text: "No matter how cloudy it gets, there's always a silver lining somewhere", isCorrect: false },
        { id: 2, text: "Every dark thing has some shiny parts to it", isCorrect: false },
        { id: 3, text: "Every difficult situation has a positive side", isCorrect: true },
      ],
      answer: "Every difficult situation has a positive side",
    },
    {
      id: "Q21",
      text: `impeccable`,
      options: [
        { id: 0, text: "faulty", isCorrect: false },
        { id: 1, text: "unreliable", isCorrect: false },
        { id: 2, text: "flawless", isCorrect: true },
        { id: 3, text: "prudent", isCorrect: false },
      ],
      answer: "flawless",
    },
    {
      id: "Q22",
      text: `Which of the following is an antonym of the word 'excited'?`,
      options: [
        { id: 0, text: "elated", isCorrect: false },
        { id: 1, text: "ecstatic", isCorrect: false },
        { id: 2, text: "exhilarated", isCorrect: false },
        { id: 3, text: "apathetic", isCorrect: true },
      ],
      answer: "apathetic",
    },
    {
      id: "Q23",
      text: `Elena's brilliant performance is in sharp contrast ....her sister's.`,
      options: [
        { id: 0, text: "for", isCorrect: false },
        { id: 1, text: "from", isCorrect: false },
        { id: 2, text: "to", isCorrect: true },
        { id: 3, text: "on", isCorrect: false },
      ],
      answer: "to",
    },
    {
      id: "Q24",
      text: `No woman .... a poor man .... a rich man.`,
      options: [
        { id: 0, text: "prefer/to", isCorrect: false },
        { id: 1, text: "prefer/than", isCorrect: false },
        { id: 2, text: "prefers/than", isCorrect: false },
        { id: 3, text: "prefers/to", isCorrect: true },
      ],
      answer: "prefers/to",
    },
    {
      id: "Q25",
      text: `What is the plural form of 'man servant'?`,
      options: [
        { id: 0, text: "men servants", isCorrect: true },
        { id: 1, text: "men servant", isCorrect: false },
        { id: 2, text: "man servants", isCorrect: false },
        { id: 3, text: "man servant", isCorrect: false },
      ],
      answer: "men servants",
    },
    {
      id: "Q26",
      text: `This t-shirt is a bit .... around the neck.`,
      options: [
        { id: 0, text: "loose", isCorrect: true },
        { id: 1, text: "lose", isCorrect: false },
        { id: 2, text: "loss", isCorrect: false },
        { id: 3, text: "lost", isCorrect: false },
      ],
      answer: "loose",
    },
    {
      id: "Q27",
      text: `The rickety bus went slower and slower until it stopped .....`,
      options: [
        { id: 0, text: "al together", isCorrect: false },
        { id: 1, text: "alltogether", isCorrect: false },
        { id: 2, text: "altogether", isCorrect: true },
        { id: 3, text: "all together", isCorrect: false },
      ],
      answer: "altogether",
    },
    {
      id: "Q28",
      text: `The goal could not have come at a more .... moment.`,
      options: [
        { id: 0, text: "opportune", isCorrect: true },
        { id: 1, text: "oppotuned", isCorrect: false },
        { id: 2, text: "opportunity", isCorrect: false },
        { id: 3, text: "oppone", isCorrect: false },
      ],
      answer: "opportune",
    },
    {
      id: "Q29",
      text: `The .... of Covid-19 brought more economic crises than it did, ill-health.`,
      options: [
        { id: 0, text: "outset", isCorrect: false },
        { id: 1, text: "on set", isCorrect: false },
        { id: 2, text: "onset", isCorrect: true },
        { id: 3, text: "out set",  isCorrect: false },
      ],
      answer: "onset",
    },
    {
      id: "Q30",
      text: `Her ..... endears her to many a student.`,
      options: [
        { id: 0, text: "childishness", isCorrect: false },
        { id: 1, text: "childlikeness", isCorrect: true },
        { id: 2, text: "childlike", isCorrect: false },
        { id: 3, text: "childish", isCorrect: false },
      ],
      answer: "childlikeness",
    },
    {
      id: "Q31",
      text: `The ............... is indeed a very humorous person.`,
      options: [
        { id: 0, text: "master of ceremonies", isCorrect: true },
        { id: 1, text: "masters of ceremonies", isCorrect: false },
        { id: 2, text: "master of ceremony", isCorrect: false },
        { id: 3, text: "masters of ceremony", isCorrect: false },
      ],
      answer: "master of ceremonies",
    },
    {
      id: "Q32",
      text: `Barcelona was an ..... team during the Messi era.`,
      options: [
        { id: 0, text: "invincible", isCorrect: true },
        { id: 1, text: "invisible", isCorrect: false },
        { id: 2, text: "invicible", isCorrect: false },
        { id: 3, text: "invinsible", isCorrect: false },
      ],
      answer: "invincible",
    },
    {
      id: "Q33",
      text: `Despite his rude manners, she accepted his assistance, afterall ...`,
      options: [
        { id: 0, text: "beggars have no choice", isCorrect: false },
        { id: 1, text: "beggars are choiceless", isCorrect: false },
        { id: 2, text: "beggars can't be choosers", isCorrect: true },
        { id: 3, text: "beggars can't make choices", isCorrect: false },
      ],
      answer: "beggars can't be choosers",
    },
    {
      id: "Q34",
      text: `She finds it .... being summoned by a younger person.`,
      options: [
        { id: 0, text: "quite insultive", isCorrect: false },
        { id: 1, text: "quit insulting", isCorrect: false },
        { id: 2, text: "quit insultive", isCorrect: false },
        { id: 3, text: "quite insulting", isCorrect: true },
      ],
      answer: "quite insulting",
    },
    {
      id: "Q35",
      text: `She claims she was..... his proposal.`,
      options: [
        { id: 0, text: "coaxed into accepting", isCorrect: false },
        { id: 1, text: "coerced into accepting", isCorrect: true },
        { id: 2, text: "coersed into accepting", isCorrect: false },
        { id: 3, text: "coerced to accept", isCorrect: false },
      ],
      answer: "coerced into accepting",
    },
    {
      id: "Q36",
      text: `She's pretty good at driving.`,
      options: [
        { id: 0, text: "she's fairly good at driving", isCorrect: false },
        { id: 1, text: "she's very good at driving", isCorrect: true },
        { id: 2, text: "she's not good at driving at all", isCorrect: false },
        { id: 3, text: "she's an excellent driver", isCorrect: false },
      ],
      answer: "she's very good at driving",
    },
    {
      id: "Q37",
      text: `She was ..... Ogunlana bus stop.`,
      options: [
        { id: 0, text: "dropped off at", isCorrect: true },
        { id: 1, text: "dropped of at", isCorrect: false },
        { id: 2, text: "dropped at", isCorrect: false },
        { id: 3, text: "dropped off of", isCorrect: false },
      ],
      answer: "dropped off at",
    },
    {
      id: "Q38",
      text: `You are not your usual cheerful self today.`,
      options: [
        { id: 0, text: "You are as happy as you used to be", isCorrect: false },
        { id: 1, text: "You are as sad as you used to be", isCorrect: false },
        { id: 2, text: "You are not as sad as you used to be", isCorrect: false },
        { id: 3, text: "You are not as happy as you used to be", isCorrect: true },
      ],
      answer: "You are not as happy as you used to be",
    },
    {
      id: "Q39",
      text: `By next June, he ....... four novels.[UME]`,
      options: [
        { id: 0, text: "will write", isCorrect: false },
        { id: 1, text: "is writing", isCorrect: false },
        { id: 2, text: "will have written", isCorrect: true },
        { id: 3, text: "had written", isCorrect: false },
      ],
      answer: "will have written",
    },
    {
      id: "Q40",
      text: `By the end of the football match today, we ..... the best player.[UME]`,
      options: [
        { id: 0, text: "could have known", isCorrect: false },
        { id: 1, text: "might have known", isCorrect: false },
        { id: 2, text: "will have known", isCorrect: true },
        { id: 3, text: "would have known", isCorrect: false },
      ],
      answer: "will have known",
    },
    {
      id: "Q41",
      text: `You had better .... the rain before you catch a cold.`,
      options: [
        { id: 0, text: "leave", isCorrect: true },
        { id: 1, text: "left", isCorrect: false },
        { id: 2, text: "live", isCorrect: false },
        { id: 3, text: "lived", isCorrect: false },
      ],
      answer: "leave",
    },
    {
      id: "Q42",
      text: `Adenike is taller than ....`,
      options: [
        { id: 0, text: "me", isCorrect: false },
        { id: 1, text: "us", isCorrect: false },
        { id: 2, text: "them", isCorrect: false},
        { id: 3, text: "I", isCorrect: true },
      ],
      answer: "I",
    },
    {
      id: "Q43",
      text: `Every one of the stolen cars .... been recovered.`,
      options: [
        { id: 0, text: "had", isCorrect: false },
        { id: 1, text: "have", isCorrect: false },
        { id: 2, text: "has", isCorrect: true },
        { id: 3, text: "having", isCorrect: false },
      ],
      answer: "has",
    },
    {
      id: "Q44",
      text: `Four hours .... been spent on the laundry.`,
      options: [
        { id: 0, text: "have", isCorrect: false },
        { id: 1, text: "is", isCorrect: false },
        { id: 2, text: "had", isCorrect: false },
        { id: 3, text: "has", isCorrect: true },
      ],
      answer: "has",
    },
    {
      id: "Q45",
      text: `The woman, along with hundreds of others, ..... been without a job since The Lockdown.`,
      options: [
        { id: 0, text: "will", isCorrect: false },
        { id: 1, text: "was", isCorrect: false },
        { id: 2, text: "have", isCorrect: false },
        { id: 3, text: "has", isCorrect: true },
      ],
      answer: "has",
    },
    {
      id: "Q46",
      text: `...... ignored the beggar's plea for mercy.`,
      options: [
        { id: 0, text: "Passers-by", isCorrect: true },
        { id: 1, text: "Passer-by", isCorrect: false },
        { id: 2, text: "Passer-bys", isCorrect: false },
        { id: 3, text: "Passers-bys", isCorrect: false },
      ],
      answer: "Passers-by",
    },
    {
      id: "Q47",
      text: `One of the kidnappers who .... arrested a fortnight ago ....committed suicide.`,
      options: [
        { id: 0, text: "was / has ", isCorrect: false },
        { id: 1, text: "were/ have", isCorrect: false },
        { id: 2, text: "was / have", isCorrect: false },
        { id: 3, text: "were/ has", isCorrect: true },
      ],
      answer: "were/ has",
    },
    {
      id: "Q48",
      text: `This is the woman .... husband was shot.`,
      options: [
        { id: 0, text: "which", isCorrect: false },
        { id: 1, text: "whom", isCorrect: false },
        { id: 2, text: "whose", isCorrect: true },
        { id: 3, text: "who", isCorrect: false },
      ],
      answer: "whose",
    },
    {
      id: "Q49",
      text: `I have the right to appoint ...... I wish.`,
      options: [
        { id: 0, text: "whomsover", isCorrect: true },
        { id: 1, text: "whosoever", isCorrect: false },
        { id: 2, text: "who", isCorrect: false },
        { id: 3, text: "whose", isCorrect: false },
      ],
      answer: "whomsover",
    },
    {
      id: "Q50",
      text: `He charges an arm and a leg for his services.`,
      options: [
        { id: 0, text: "He is a money ritualist", isCorrect: false },
        { id: 1, text: "His services attract very little cost", isCorrect: false },
        { id: 2, text: "He offers very expensive services", isCorrect: true },
        { id: 3, text: "You will have to exchange your arm and leg for his services", isCorrect: false },
      ],
      answer: "He offers very expensive services",
    },
  ];
  export default questions;